### ISSUE TITLE
Feature request: SSL certificate verification

### ISSUE THREAD

**Issue by JanPetterMG** [bee4/transport#11]
Is it possible to add an integrated SSL certificate verification, just like GuzzleHttp does?
http://docs.guzzlephp.org/en/latest/request-options.html#verify-option

I'm working on a switch from GuzzleHttp to your library, and this is my biggest concern. To check (up to) 8 paths, that will require more code than the code needed to utilize your library combined.

There is no problem writing this code outside this library, per client basis, but everything would be so much easier if it already was integrated. I'm mainly concerned about cross system support.

How about populating `CURLOPT_CAINFO` with an auto-detected file path, when it's not already populated? (as long as `CURLOPT_SSL_VERIFYPEER` or `CURLOPT_SSL_VERIFYHOST` is activated)

**Comment by shulard** [comment]
Hello !

I think it's an awesome idea. I already faced some problems with the SSL certificate validation. What do you think here, we must check each of the eight paths and populate data accordingly ?

This feature require something new in the lib : meta options (options that can be set and are not related to any of the adapters).

I've already used something like that but I'm not sure it's the right way to do that :

```php
<?php
$options = [
    CURLOPT_SSL_VERIFYHOST => 2,
    CURLOPT_SSL_VERIFYPEER => 1,
    CURLOPT_CAINFO => PathHelper::doc().'/cacert.pem'
];
$response = $client
    ->get($url)
    ->addOptions($options)
    ->send();
```

Have you already implemented SSL validation in your project ?

I'm really glad that you choose my lib to move your project forward 👍 

For sure, we must populate the curl options whith the right values here. Maybe we can use a kind of decorator to add the SSL verification feature on the basic adapter ?

**Comment by JanPetterMG** [comment]
I agree, an method to auto-detect and fill in the path would probably be a great option. :+1: only downside is that it needs to be well documented, so that developers actually are aware of that handy method...

Haven't implemented SSL validation in any of my projects yet, just started the migration from Guzzle, where it was all integrated... I haven't much certificate validation experience either...

-----------------------

I'm not sure if this is a good or catastrophic idea, but what about adding support for an configuration array just like the one Guzzle uses? Most of Guzzle's config options are easy to convert to cURL options.
Then we don't need an public accessible method for path detection. Optionally, the cURL options still can override the config array...

Here's just a quick draft, based on one of my existing guzzle configurations (with just a few quick deletions):
```php
$config = [
    'allow_redirects' => [
        'max' => CURLOPT_MAXREDIRS,
        'referer' => CURLOPT_AUTOREFERER,
    ],
    'connect_timeout' => CURLOPT_CONNECTTIMEOUT,
    'headers' => [
        CURLOPT_HTTPHEADER,
        'accept-encoding' => CURLOPT_ENCODING,
        'user-agent' => CURLOPT_USERAGENT,
    ],
    'http_errors' => CURLOPT_FAILONERROR,
    'timeout' => CURLOPT_TIMEOUT,
    'verify' => CURLOPT_SSL_VERIFYHOST + CURLOPT_SSL_VERIFYPEER + CURLOPT_CAINFO,
];
````
My suggestion would be putting such an input parameter in the ``Client`` class for example...

**Comment by shulard** [comment]
For sure it's a nice idea to have some standard parameters that can be set directly from the Client. Personaly, I prefer a new configuration object that must be instantiated and injected in the Client (or a default will be built when necessary).

I'll start a new branch for that.

**Comment by JanPetterMG** [comment]
This isn't an issue on PHP >=5.6, but here is Guzzle's implementation for CA-bundle detection. It's actually quite simple.
```php
/**
 * Returns the default cacert bundle for the current system.
 *
 * First, the openssl.cafile and curl.cainfo php.ini settings are checked.
 * If those settings are not configured, then the common locations for
 * bundles found on Red Hat, CentOS, Fedora, Ubuntu, Debian, FreeBSD, OS X
 * and Windows are checked. If any of these file locations are found on
 * disk, they will be utilized.
 *
 * Note: the result of this function is cached for subsequent calls.
 *
 * @return string
 * @throws \RuntimeException if no bundle can be found.
 */
function default_ca_bundle()
{
    static $cached = null;
    static $cafiles = [
        // Red Hat, CentOS, Fedora (provided by the ca-certificates package)
        '/etc/pki/tls/certs/ca-bundle.crt',
        // Ubuntu, Debian (provided by the ca-certificates package)
        '/etc/ssl/certs/ca-certificates.crt',
        // FreeBSD (provided by the ca_root_nss package)
        '/usr/local/share/certs/ca-root-nss.crt',
        // OS X provided by homebrew (using the default path)
        '/usr/local/etc/openssl/cert.pem',
        // Google app engine
        '/etc/ca-certificates.crt',
        // Windows?
        'C:\\windows\\system32\\curl-ca-bundle.crt',
        'C:\\windows\\curl-ca-bundle.crt',
    ];
    if ($cached) {
        return $cached;
    }
    if ($ca = ini_get('openssl.cafile')) {
        return $cached = $ca;
    }
    if ($ca = ini_get('curl.cainfo')) {
        return $cached = $ca;
    }
    foreach ($cafiles as $filename) {
        if (file_exists($filename)) {
            return $cached = $filename;
        }
    }
    throw new \RuntimeException(<<< EOT
No system CA bundle could be found in any of the the common system locations.
PHP versions earlier than 5.6 are not properly configured to use the system's
CA bundle by default. In order to verify peer certificates, you will need to
supply the path on disk to a certificate bundle to the 'verify' request
option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do not
need a specific certificate bundle, then Mozilla provides a commonly used CA
bundle which can be downloaded here (provided by the maintainer of cURL):
https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. Once
you have a CA bundle available on disk, you can set the 'openssl.cafile' PHP
ini setting to point to the path to the file, allowing you to omit the 'verify'
request option. See http://curl.haxx.se/docs/sslcerts.html for more
information.
EOT
    );
}
````
Source: https://github.com/guzzle/guzzle/blob/d094e337976dff9d8e2424e8485872194e768662/src/functions.php#L161

**Comment by shulard** [comment]
The implementation seems really clean. I think I'll just create a specific exception for that. Thanks for the details!

**Comment by JanPetterMG** [comment]
No, sorry... 
But I'll just stumbled upon the [composer/ca-bundle](https://github.com/composer/ca-bundle) repo. Makes it super-easy to detect the CA path. :smile:
```php
$curl = curl_init("https://example.org/");
curl_setopt($curl, CURLOPT_CAINFO, \Composer\CaBundle\CaBundle::getSystemCaRootBundlePath());
$result = curl_exec($curl);
````
It even has validation methods built in.
- `CaBundle::getSystemCaRootBundlePath()`: Returns the system CA bundle path, or a path to the bundled one as fallback
- `CaBundle::getBundledCaBundlePath()`: Returns the path to the bundled CA file
- `CaBundle::validateCaFile($filename)`: Validates a CA file using opensl_x509_parse only if it is safe to use
- `CaBundle::isOpensslParseSafe()`: Test if it is safe to use the PHP function openssl_x509_parse()
- `CaBundle::reset()`: Resets the static caches

Source: [README.md](https://github.com/composer/ca-bundle#composercabundlecabundle)

From now on, my preferred solution :smiley:

**Comment by shulard** [comment]
For sure, this is the better solution for me too (composer libraries offer top quality components).

**Comment by JanPetterMG** [comment]
Then I guess we can close this one...
In the future, if anyone asks about SSL/TLS verification, just point them to [composer/ca-bundle](https://github.com/composer/ca-bundle).

**Comment by shulard** [comment]
I think I'll embed some configurations logic inside this lib to add a curl agnostic layer on top of it. I'll use that package for the verification mechanism. Thanks for your researchs 👍
