### ISSUE TITLE
How to get CURLINFO_* values

### ISSUE THREAD

**Issue by JanPetterMG** [bee4/transport#14]
How to fetch the ``CURLINFO_EFFECTIVE_URL`` value, or any ``CURLINFO_*`` value in general?

cURL example
```php
$value = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
```

What method did I overlooked?

**Comment by shulard** [comment]
To retrieve these informations you can use the `getInfo` method given by the `AbstractAdapter` : https://github.com/bee4/transport/blob/master/src/Handle/AbstractHandle.php#L46

All the details given by `curl_getinfo` are stored in an array after request execution: https://github.com/bee4/transport/blob/master/src/Handle/CurlHandle.php#L99

Hope this help 😄

**Comment by JanPetterMG** [comment]
I'm not sure how to get to that method, maybe I'm doing it the wrong way?
```php
            $client = new Bee4\Transport\Client($baseUri);
            $request = $client->createRequest('GET', $path);
            $request->addOptions($curlOptions);
            $this->response = $request->send();
            $this->statusCode = $this->response->getStatus();
            $this->contents = $this->response->getBody();
```
Shouldn't there be some way to fetch that array / curlinfo_* from the returning class of the ``$request->send()`` method?
```php
$this->response = $request->send();
$url = $this->response->getInfo(CURLINFO_EFFECTIVE_URL);
```

**Comment by shulard** [comment]
Hum you are right, the `CurlHandle` instance is embedded in the Client...

Do you think the best way is to attach the `Handle` to the `Response` or to add a method to the Client and retrieve it ?

**Comment by shulard** [comment]
I think there is actually a way to retrieve that details :

```
<?php
$request = (new Bee4\Transport\Client())->createRequest('GET', 'http://example.org');
$response = $request->send();

$handle = Bee4\Transport\Handle\HandleFactory::build($request);
$info = $handle->getInfo(CURLINFO_EFFECTIVE_URL);
```

What do you think about that method ? It does not seem really clean to me but it works...

**Comment by JanPetterMG** [comment]
I must agree, it works, but it isn't the ideal.

No hurry, but maybe in version 2.0 or if possible in 1.3, find a cleaner method, preferably from the response class.

**Comment by shulard** [comment]
I've worked on a new way to deal with cURL handle and executions details. Can you take a look on the `feature/configuration` branch ?

I've introduced a new object, `ExecutionInfos` which is injected in the `Response` so you can run :

```php
$infos = $response->getExecutionInfos();
$infos->getHandle(); //Here return the CurlHandle instance used...
```

These changes will be published in the v2.0 because it's a huge modification of the core API...

**Comment by JanPetterMG** [comment]
Looks good to me :+1:

**Comment by shulard** [comment]
Thanks for the review 👍. I think I'll tag the v2.0.0 soon.
